server:
  port: 8000
spring:
  jpa:
    open-in-view: true
  datasource:
    url: ${DATABASE_URI}
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=products
#    url: ${DATABASE_USER}
    username: ${DATABASE_USER}
#    username: postgres
#    password: postgres
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
          hbm2ddl.auto: validate
          show_sql: true
          format_sql: true
    flyway:
      enabled: false
#      schemas: user_domain
#      url: jdbc:postgresql://localhost:5432/postgres
#      user: ${DATABASE_USER}
#      password: ${DATABASE_PASSWORD}



# enable percentile-based histogram for http requests
#management.metrics.distribution.percentiles-histogram.http.server.requests: true
# http SLA histogram buckets
#management.metrics.distribution.sla.http.server.requests: 100ms,150ms,250ms,500ms,1s
# enable JVM metrics
#management.metrics.enable.jvm: true

products-app:
  cache-enabled: ${CACHE_ENABLED}

spring.cache.type: redis
spring.redis.host: ${REDIS_HOST}
#spring.redis.host: localhost
#spring.redis.host: 192.168.99.100
spring.redis.port: 6379
#spring.redis.port: ${REDIS_PORT}
#  6379